title: CBYun-Blog
description: "ChatGPT와 함께하는 인생 2막 기록"
theme: minima
markdown: kramdown
show_excerpts: true
author: 윤창배

# 상단 메뉴에 표시할 페이지들 (선택적으로 나중에 만들면 자동 표시)
header_pages:
  - about.md
  - category.md

# 소셜 링크 (선택)
github_username: cbyun73
